In [1]:
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
import joblib

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from xgboost import XGBRegressor

In [2]:
X = np.array([[1,-2,3],[2,5,-7],[6,8,-10],[-7,8,-10],[0,8,-10],[6,0,-3],[-12,2,-12],[1,8,-10],[6,7,-3]])

y = []

for elements in X:

    y_temp = elements[0]^2 + elements[1] + elements[2]
    y.append(y_temp)
y =np.array(y)
print(y)

[ 2  2  6 -7  0 -7 12  1  0]


In [3]:
pipe1 = Pipeline([
    ('scalar',StandardScaler()),
    ('modeling',LinearRegression())
])

pipe1.fit(X,y)
y_pred = pipe1.predict(X)

print(y_pred)
print(y)

[-1.34215594  1.00590588  1.0458938   1.00801277  1.02841025  1.73002102
  7.0142171   1.03132417 -3.52162906]
[ 2  2  6 -7  0 -7 12  1  0]


In [4]:
pipe2 = Pipeline([
    ('scalar',StandardScaler()),
    ('modeling',XGBRegressor())
])

pipe2.fit(X,y)
y_pred = pipe2.predict(X)

print(y_pred)
print(y)

[ 1.9994839e+00  1.9998760e+00  5.9982829e+00 -6.9985585e+00
  2.6213750e-04 -6.9981656e+00  1.1998822e+01  1.0000918e+00
 -9.5302697e-05]
[ 2  2  6 -7  0 -7 12  1  0]


In [5]:
joblib.dump(pipe2,'model_temp.joblib')

['model_temp.joblib']

In [6]:
load_model = joblib.load('model_temp.joblib')

In [7]:
load_model.predict(X)

array([ 1.9994839e+00,  1.9998760e+00,  5.9982829e+00, -6.9985585e+00,
        2.6213750e-04, -6.9981656e+00,  1.1998822e+01,  1.0000918e+00,
       -9.5302697e-05], dtype=float32)

In [8]:
output = {'output':load_model.predict(X)}

print(output)


{'output': array([ 1.9994839e+00,  1.9998760e+00,  5.9982829e+00, -6.9985585e+00,
        2.6213750e-04, -6.9981656e+00,  1.1998822e+01,  1.0000918e+00,
       -9.5302697e-05], dtype=float32)}


In [9]:
c= load_model.predict([[1,2,3]])
load_model.predict([[1,2,3]])

array([1.9995149], dtype=float32)

In [10]:
c.dtype

dtype('float32')

In [11]:
c.tolist()

[1.9995149374008179]

In [12]:
c[0]

1.9995149

In [13]:
columns = ['one','two','three']

data = pd.DataFrame(data = X, columns=columns)
data

one  two  three
0    1   -2      3
1    2    5     -7
2    6    8    -10
3   -7    8    -10
4    0    8    -10
5    6    0     -3
6  -12    2    -12
7    1    8    -10
8    6    7     -3